In [1]:
from datasets import load_dataset
import pandas as pd

In [2]:
dataset = load_dataset('lukebarousse/data_jobs')

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

README.md:   0%|          | 0.00/3.25k [00:00<?, ?B/s]

data_jobs.csv: reconstructing file:   0%|          |  0.00B /  231MB

data_jobs.csv: downloading bytes:           |  0.00B

Generating train split:   0%|          | 0/785741 [00:00<?, ? examples/s]

In [3]:
dataset["train"]

Dataset({
    features: ['job_title_short', 'job_title', 'job_location', 'job_via', 'job_schedule_type', 'job_work_from_home', 'search_location', 'job_posted_date', 'job_no_degree_mention', 'job_health_insurance', 'job_country', 'salary_rate', 'salary_year_avg', 'salary_hour_avg', 'company_name', 'job_skills', 'job_type_skills'],
    num_rows: 785741
})

In [4]:
df = dataset["train"].to_pandas()

In [5]:
df.describe()

       salary_year_avg  salary_hour_avg
count     22003.000000     10662.000000
mean     123286.274072        47.016598
std       48312.449482        21.890738
min       15000.000000         8.000000
25%       90000.000000        27.500000
50%      115000.000000        45.980000
75%      150000.000000        61.159996
max      960000.000000       391.000000

In [6]:
df.count()

job_title_short          785741
job_title                785740
job_location             784696
job_via                  785733
job_schedule_type        773074
job_work_from_home       785741
search_location          785741
job_posted_date          785741
job_no_degree_mention    785741
job_health_insurance     785741
job_country              785692
salary_rate               33067
salary_year_avg           22003
salary_hour_avg           10662
company_name             785723
job_skills               668704
job_type_skills          668704
dtype: int64

In [7]:
df.count()

job_title_short          785741
job_title                785740
job_location             784696
job_via                  785733
job_schedule_type        773074
job_work_from_home       785741
search_location          785741
job_posted_date          785741
job_no_degree_mention    785741
job_health_insurance     785741
job_country              785692
salary_rate               33067
salary_year_avg           22003
salary_hour_avg           10662
company_name             785723
job_skills               668704
job_type_skills          668704
dtype: int64

In [8]:
df["salary_year_avg"].min()

15000.0

In [9]:
df["salary_year_avg"].idxmin()

665729

In [10]:
min_salary = df["salary_year_avg"].idxmin()

In [11]:
df.iloc[min_salary]

job_title_short                                              Data Engineer
job_title                                           Data Engineer - Hadoop
job_location                                                        Brazil
job_via                                                       via LinkedIn
job_schedule_type                                                Full-time
job_work_from_home                                                   False
search_location                                                     Brazil
job_posted_date                                        2023-12-09 10:05:30
job_no_degree_mention                                                 True
job_health_insurance                                                 False
job_country                                                         Brazil
salary_rate                                                           year
salary_year_avg                                                    15000.0
salary_hour_avg                                                        NaN
company_name                                               Net2Source Inc.
job_skills               ['java', 'python', 'oracle', 'aws', 'hadoop', ...
job_type_skills          {'cloud': ['oracle', 'aws'], 'libraries': ['ha...
Name: 665729, dtype: object

In [12]:
#check the max salary
df["salary_year_avg"].max()

960000.0

In [13]:
#index of the maximum salary
df["salary_year_avg"].idxmax()

554784

In [14]:
max_salary = df["salary_year_avg"].idxmax()

In [15]:
df.iloc[max_salary]

job_title_short                                           Data Scientist
job_title                                                 Data Scientist
job_location                                                 Madison, SD
job_via                                    via Cooperative Career Center
job_schedule_type                                              Full-time
job_work_from_home                                                 False
search_location                                  Illinois, United States
job_posted_date                                      2023-05-04 19:06:06
job_no_degree_mention                                              False
job_health_insurance                                                True
job_country                                                United States
salary_rate                                                         year
salary_year_avg                                                 960000.0
salary_hour_avg                                                      NaN
company_name                 East River Electric Power Cooperative, Inc.
job_skills                                ['java', 'c++', 'python', 'r']
job_type_skills          {'programming': ['java', 'c++', 'python', 'r']}
Name: 554784, dtype: object

In [16]:
df["job_title_short"].unique()

array(['Senior Data Engineer', 'Data Analyst', 'Data Engineer',
       'Business Analyst', 'Data Scientist', 'Machine Learning Engineer',
       'Senior Data Analyst', 'Cloud Engineer', 'Senior Data Scientist',
       'Software Engineer'], dtype=object)

In [17]:
df["job_title_short"].value_counts()

job_title_short
Data Analyst                 196075
Data Engineer                186241
Data Scientist               172286
Business Analyst              49063
Software Engineer             44929
Senior Data Engineer          44563
Senior Data Scientist         36957
Senior Data Analyst           29216
Machine Learning Engineer     14080
Cloud Engineer                12331
Name: count, dtype: int64

In [18]:
df.groupby("job_title_short")["salary_year_avg"].min()

job_title_short
Business Analyst             16500.0
Cloud Engineer               42000.0
Data Analyst                 25000.0
Data Engineer                15000.0
Data Scientist               27000.0
Machine Learning Engineer    30000.0
Senior Data Analyst          30000.0
Senior Data Engineer         35000.0
Senior Data Scientist        45000.0
Software Engineer            28000.0
Name: salary_year_avg, dtype: float64

In [19]:
df.groupby("job_title_short")[["salary_year_avg","salary_hour_avg"]].max()

                           salary_year_avg  salary_hour_avg
job_title_short
Business Analyst                  387460.0            132.5
Cloud Engineer                    280000.0             91.0
Data Analyst                      650000.0            391.0
Data Engineer                     525000.0            184.5
Data Scientist                    960000.0            237.5
Machine Learning Engineer         325000.0             87.5
Senior Data Analyst               425000.0            130.0
Senior Data Engineer              425000.0            170.0
Senior Data Scientist             890000.0            150.0
Software Engineer                 375000.0            102.5

In [20]:
df.groupby("job_title_short")[["salary_year_avg","salary_hour_avg"]].agg(['min','max','median'])

                          salary_year_avg                     salary_hour_avg  \
                                      min       max    median             min
job_title_short
Business Analyst                  16500.0  387460.0   85000.0          10.835
Cloud Engineer                    42000.0  280000.0   90000.0          18.500
Data Analyst                      25000.0  650000.0   90000.0           8.000
Data Engineer                     15000.0  525000.0  125000.0           8.000
Data Scientist                    27000.0  960000.0  127500.0           8.000
Machine Learning Engineer         30000.0  325000.0  106415.0          10.000
Senior Data Analyst               30000.0  425000.0  111175.0          13.000
Senior Data Engineer              35000.0  425000.0  147500.0          12.500
Senior Data Scientist             45000.0  890000.0  155500.0          17.500
Software Engineer                 28000.0  375000.0   99150.0          11.000


                             max     median
job_title_short
Business Analyst           132.5  40.362499
Cloud Engineer              91.0  40.000000
Data Analyst               391.0  32.615002
Data Engineer              184.5  58.500000
Data Scientist             237.5  47.500000
Machine Learning Engineer   87.5  47.535000
Senior Data Analyst        130.0  47.500000
Senior Data Engineer       170.0  61.500000
Senior Data Scientist      150.0  47.620003
Software Engineer          102.5  47.560001

In [21]:
df.groupby("job_title_short")["salary_year_avg"].agg(['min','max','median'])

                               min       max    median
job_title_short
Business Analyst           16500.0  387460.0   85000.0
Cloud Engineer             42000.0  280000.0   90000.0
Data Analyst               25000.0  650000.0   90000.0
Data Engineer              15000.0  525000.0  125000.0
Data Scientist             27000.0  960000.0  127500.0
Machine Learning Engineer  30000.0  325000.0  106415.0
Senior Data Analyst        30000.0  425000.0  111175.0
Senior Data Engineer       35000.0  425000.0  147500.0
Senior Data Scientist      45000.0  890000.0  155500.0
Software Engineer          28000.0  375000.0   99150.0

In [22]:
df.columns

Index(['job_title_short', 'job_title', 'job_location', 'job_via',
       'job_schedule_type', 'job_work_from_home', 'search_location',
       'job_posted_date', 'job_no_degree_mention', 'job_health_insurance',
       'job_country', 'salary_rate', 'salary_year_avg', 'salary_hour_avg',
       'company_name', 'job_skills', 'job_type_skills'],
      dtype='object')

In [23]:
df["job_country"].value_counts().head(20)

job_country
United States     206292
India              51088
United Kingdom     40375
France             39922
Germany            27694
Spain              25100
Singapore          23696
Sudan              21781
Netherlands        20631
Italy              17013
Canada             16029
Mexico             15139
Poland             14793
Portugal           14508
Australia          12955
South Africa       12414
Belgium            12078
Philippines        11786
Ireland            11162
Switzerland         9924
Name: count, dtype: int64

In [24]:
df["job_country"].isin(["Brazil"]).any()

np.True_

In [25]:
us_jobs =df[df["job_country"] == "United States"]

In [26]:
us_jobs

,job_title_short,job_title,job_location,job_via,job_schedule_type,job_work_from_home,search_location,job_posted_date,job_no_degree_mention,job_health_insurance,job_country,salary_rate,salary_year_avg,salary_hour_avg,company_name,job_skills,job_type_skills
0,Senior Data Engineer,Senior Clinical Data Engineer / Principal Clin...,"Watertown, CT",via Work Nearby,Full-time,False,"Texas, United States",2023-06-16 13:44:15,False,False,United States,None,NaN,NaN,Boehringer Ingelheim,None,None
3,Data Engineer,LEAD ENGINEER - PRINCIPAL ANALYST - PRINCIPAL ...,"San Antonio, TX",via Diversity.com,Full-time,False,"Texas, United States",2023-07-04 13:01:41,True,False,United States,None,NaN,NaN,Southwest Research Institute,"['python', 'c++', 'java', 'matlab', 'aws', 'te...","{'cloud': ['aws'], 'libraries': ['tensorflow',..."
5,Data Engineer,GCP Data Engineer,Anywhere,via ZipRecruiter,Contractor and Temp work,True,Georgia,2023-11-07 14:01:59,False,False,United States,None,NaN,NaN,smart folks inc,"['python', 'sql', 'gcp']","{'cloud': ['gcp'], 'programming': ['python', '..."
6,Senior Data Engineer,Senior Data Engineer - GCP Cloud,"Dearborn, MI",via LinkedIn,Full-time,False,"Florida, United States",2023-03-27 13:18:18,False,False,United States,None,NaN,NaN,"Miracle Software Systems, Inc","['sql', 'python', 'java', 'sql server', 'gcp',...","{'cloud': ['gcp', 'bigquery'], 'databases': ['..."
9,Data Scientist,Data Scientist II,Anywhere,via ZipRecruiter,Full-time,True,"New York, United States",2023-04-23 13:02:57,False,False,United States,None,NaN,NaN,"Radwell International, LLC","['sql', 'python', 'r', 'mongodb', 'mongodb', '...","{'analyst_tools': ['excel'], 'cloud': ['azure'..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
785673,Data Scientist,Asset Management Data Scientist,"New York, NY",via Trabajo.org,Full-time,False,"New York, United States",2023-10-16 06:01:53,True,False,United States,None,NaN,NaN,JPMorgan Chase & Co.,None,None
785685,Data Analyst,Data Analyst,"Indianapolis, IN",via Trabajo.org,Full-time,False,"Illinois, United States",2023-07-16 06:01:27,True,False,United States,None,NaN,NaN,"Aara Technologies, Inc","['sql', 'excel']","{'analyst_tools': ['excel'], 'programming': ['..."
785692,Data Scientist,Data Scientist- Hybrid Work Location,"Dayton, OH",via Ai-Jobs.net,Full-time,False,"Illinois, United States",2023-04-21 06:02:31,False,True,United States,year,157500.0,NaN,Tenet3,"['python', 'matlab', 'r']","{'programming': ['python', 'matlab', 'r']}"
785703,Data Analyst,Data Analyst - CRYPTOGRAPHY - Full-time,Anywhere,via Snagajob,Full-time,True,"Texas, United States",2023-01-28 06:02:55,True,False,United States,None,NaN,NaN,Axelon Services Corporation,None,None
785705,Data Analyst,Expert Business Data Analyst - Now Hiring,"Oakland, CA",via Snagajob,Full-time,False,"California, United States",2023-01-09 06:00:25,False,False,United States,None,NaN,NaN,PG&E Corporation,"['sql', 'python', 'tableau']","{'analyst_tools': ['tableau'], 'programming': ..."

In [27]:
us_jobs = us_jobs[us_jobs["salary_year_avg"].notna()]

In [28]:
us_jobs

,job_title_short,job_title,job_location,job_via,job_schedule_type,job_work_from_home,search_location,job_posted_date,job_no_degree_mention,job_health_insurance,job_country,salary_rate,salary_year_avg,salary_hour_avg,company_name,job_skills,job_type_skills
92,Data Engineer,Remote - Data Engineer - Permanent - W2,Anywhere,via LinkedIn,Full-time,True,"Illinois, United States",2023-02-21 13:29:59,False,True,United States,year,120000.0,NaN,Apex Systems,"['sql', 'python']","{'programming': ['sql', 'python']}"
100,Data Scientist,"Data Scientist, Risk Data Mining - USDS","Mountain View, CA",via LinkedIn,Full-time,False,"California, United States",2023-07-31 13:01:18,False,True,United States,year,228222.0,NaN,TikTok,"['sql', 'r', 'python', 'express']","{'programming': ['sql', 'r', 'python'], 'webfr..."
109,Data Analyst,Senior Supply Chain Analytics Analyst,Anywhere,via Get.It,Full-time,True,"Illinois, United States",2023-10-12 13:02:19,False,True,United States,year,89000.0,NaN,Get It Recruit - Transportation,"['python', 'r', 'alteryx', 'tableau']","{'analyst_tools': ['alteryx', 'tableau'], 'pro..."
116,Data Scientist,Data Scientist,Anywhere,via LinkedIn,Full-time,True,"Texas, United States",2023-10-04 13:04:23,False,False,United States,year,114000.0,NaN,4 Corner Resources,"['r', 'python', 'sql', 't-sql', 'hadoop', 'spa...","{'analyst_tools': ['tableau'], 'libraries': ['..."
146,Data Engineer,Data Engineer Graduate (Real Time Communicatio...,"Seattle, WA",via LinkedIn,Full-time,False,"California, United States",2023-10-21 13:06:16,False,True,United States,year,129500.0,NaN,ByteDance,"['golang', 'scala', 'python', 'java', 'hadoop'...","{'libraries': ['hadoop', 'spark'], 'programmin..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
785563,Data Scientist,Data Scientist I/II (Model Risk Management & M...,"Pensacola, FL",via Navy Federal Credit Union - Talentify,Full-time,False,"Florida, United States",2023-01-11 06:22:10,False,False,United States,year,136400.0,NaN,Navy Federal Credit Union,"['r', 'python', 'matplotlib', 'ggplot2', 'spar...","{'analyst_tools': ['word', 'power bi', 'tablea..."
785624,Data Engineer,Data Analytics Engineer (Hybrid),"Mt Prospect, IL",via Ai-Jobs.net,Full-time,False,"Illinois, United States",2023-08-31 06:02:16,False,True,United States,year,139216.0,NaN,Bosch Group,"['go', 'python', 'r', 'sql', 'oracle', 'window...","{'analyst_tools': ['alteryx', 'power bi', 'tab..."
785641,Data Engineer,Data Engineer,"New York, NY",via Dice,Full-time,False,Georgia,2023-01-04 16:36:07,True,False,United States,year,150000.0,NaN,"Engage Partners, Inc.",None,None
785648,Data Scientist,Director Data Scientist - Commercial Platforms...,"Pleasant Hill, CA",via Ai-Jobs.net,Full-time,False,"California, United States",2023-04-12 06:02:51,False,True,United States,year,221875.0,NaN,84.51°,"['python', 'azure', 'snowflake', 'spark']","{'cloud': ['azure', 'snowflake'], 'libraries':..."
785692,Data Scientist,Data Scientist- Hybrid Work Location,"Dayton, OH",via Ai-Jobs.net,Full-time,False,"Illinois, United States",2023-04-21 06:02:31,False,True,United States,year,157500.0,NaN,Tenet3,"['python', 'matlab', 'r']","{'programming': ['python', 'matlab', 'r']}"

In [29]:
us_jobs.groupby('job_title_short')["salary_year_avg"].agg(['min','max','median']).sort_values(by = 'median', ascending=False)

                               min       max    median
job_title_short
Senior Data Scientist      55000.0  475000.0  155000.0
Machine Learning Engineer  44408.5  315000.0  150000.0
Senior Data Engineer       45000.0  375000.0  150000.0
Data Scientist             30000.0  960000.0  130000.0
Software Engineer          48982.0  375000.0  130000.0
Data Engineer              23496.0  525000.0  125000.0
Cloud Engineer             42000.0  221844.0  116100.0
Senior Data Analyst        35360.0  425000.0  110000.0
Business Analyst           35000.0  387460.0   90000.0
Data Analyst               25000.0  375000.0   90000.0